name: Collect Allure environment data
description: Collects environment data and puts them into allure-results folder
runs:
  using: "composite"
  steps:
    - run: |
        ENV_FILE="environment.properties"

        export $(grep -v '^#' .env | xargs)
        echo "PROXY_URL=$PROXY_URL"

        # EVM version
        EVM_VERSION=$(curl -X POST -H 'Content-Type: application/json' -d '{"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":0}' $PROXY_URL)
        echo "EVM.Version=$EVM_VERSION" > $ENV_FILE
        
        # openzeppelin-contracts version
        cd openzeppelin-contracts
        TEST_VERSION=$(git log -n 1 | grep Date)
        TEST_AUTHOR=$(git log -n 1 | grep Author)
        cd ..
        echo "Test.Version=$TEST_VERSION" >> $ENV_FILE
        echo "Test.Commiter=$TEST_AUTHOR" >> $ENV_FILE
        
        # Solana cluster version
        SOLANA_VERSION=$(curl $PROXY_URL -X POST -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","id":1, "method":"getVersion"}')
        echo "Solana.Version=$SOLANA_VERSION" >> $ENV_FILE

        echo "$ENV_FILE content:"
        cat $ENV_FILE
      shell: bash
