name: Switch to network of choice
description: Use the network chosen in the manual input box
runs:
  using: "composite"
  steps:
    - run: |
        echo "Tags: ${{ github.event.inputs.tags }}"
        echo "Network: ${{ github.event.inputs.network }}"
        if [ -z "${{ github.event.inputs.network }}" ]
        then
          NETWORK='internal.testnet'
        else
          NETWORK="${{ github.event.inputs.network }}"
        fi
        echo "======================================"
        echo "NETWORK=$NETWORK"
        echo "INPUT_NETWORK=$INPUT_NETWORK"

        function copyEnvFile {
          echo "======================================"
          echo "copying ./.env.$NETWORK to ./$1.env"
          cp "./.env.$NETWORK" "./$1.env"
          cat "./$1.env"
        }

        copyEnvFile ""
        copyEnvFile "hardhat-advanced/"
        copyEnvFile "openzeppelin-contracts/"

        # echo ""
        # echo "copying to the hardhat-advanced folder..."
        # cp "./.env.$NETWORK" ./hardhat-advanced/.env
        # cat ./hardhat-advanced/.env

        # echo ""
        # echo "copying to the openzeppelin-contracts folder..."
        # cp "./.env.$NETWORK" ./openzeppelin-contracts/.env
        # cat ./openzeppelin-contracts/.env
      shell: bash
