name: OpenZeppelin contracts preparation
description: Downloads the submodule, creates a folder for reports and put categories.json there
runs:
  using: "composite"
  steps:
    - run: |
        rm -rf openzeppelin-contracts
        git submodule update --init --recursive
        cd openzeppelin-contracts
        echo "$ pwd"
        pwd
        cp ../hardhat.config.js .
      shell: bash
    - uses: ./.github/actions/allure-environment-data
    - run: |
        cd openzeppelin-contracts
        # categories.json
        ALLURE_RESULTS="allure-results"
        mkdir $ALLURE_RESULTS
        cp ../categories.json $ALLURE_RESULTS
        cp ../environment.json $ALLURE_RESULTS
        cp ../environment.properties $ALLURE_RESULTS
        cp ../environment.properties ../report
        cp ../environment.properties "../report/$ALLURE_RESULTS"
        echo "$ ls $ALLURE_RESULTS"
        ls $ALLURE_RESULTS
        echo "============================================================================================="
        echo "==================== the openzeppelin-contracts repo is downloaded =========================="
        echo "============================= and hardhat.config.js is here ================================="
        echo "============================================================================================="
        echo "$ ls -la"
        ls -la
      shell: bash




