name: Python 3.8, Node.js 16, allure

# on: [push]
on:
  push:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
      network:
        description: 'Network (devnet, testnet, internal.testnet, neonswap.live, ropsten, rinkeby)'
        default: 'devnet'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Switch to network of choice
      run: |
        echo "Log level: ${{ github.event.inputs.logLevel }}"
        echo "Tags: ${{ github.event.inputs.tags }}"
        echo "Network: ${{ github.event.inputs.network }}"
        echo "==================== 2 =================="
        echo $INPUT_NETWORK
        echo "./.env.$INPUT_NETWORK"
        cp "./.env.${{ github.event.inputs.network }}" ./.env
        cat ./.env

  python:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/allure-prep
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        npm i
        # python -m pip install --upgrade pip
        pip install pipenv
        pipenv sync
        # pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pipenv run flake8 ./src
        pipenv run flake8 ./tests
    - name: Test with pytest
      if: always()
      run: |
        pwd
        pipenv run pytest --alluredir=allure-results

    - name: Look at Allure
      if: always()
      uses: ./.github/actions/allure-show

    # TODO: de-duplicate
    - name: Archive Allure results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: allure-results
        path: allure-results

  allure:
    runs-on: ubuntu-latest
    if: always()
    needs:
      - build
      - python
    steps:

    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v2

    - name: Get Allure history
      uses: actions/checkout@v2
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    - name: Allure Report with history
      uses: simple-elf/allure-report-action@v1.5
      if: always()

    - name: Allure Report action from marketplace
      uses: simple-elf/allure-report-action@master
      if: always()
      with:
        allure_results: allure-results
        gh_pages: gh-pages
        allure_report: allure-report
        allure_history: allure-history
        keep_reports: 50

    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: allure-history
